volumes:
  slate:
  postgres:
  cassandra:
  valkey:

services:
#  slate:
#    build: .
#    restart: no
#    ports:
#      - "8000:8000"
#    volumes:
#      - slate:/var/lib/slatevcserver

  postgres:
    image: postgres:18
    restart: no
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql

  cassandra:
    image: cassandra:6.0
    restart: no
    ports:
      - "9042:9042"
    volumes:
      - cassandra:/var/lib/cassandra

  valkey:
    image: valkey/valkey:9
    restart: no
    ports:
      - "6379:6379"
    volumes:
      - valkey:/data